### ISSUE TITLE
Error: Unable to find workflow in example/repo 😥

### ISSUE THREAD

**Issue by rutgerth1508** [benc-uk/workflow-dispatch#21] opened 2021-05-12 09:42 UTC
I am getting an error trying to run a different workflow from the current one.
This is the step in the workflow:
```
 - name: Invoke unit test workflow
   uses: benc-uk/workflow-dispatch@v1
   with:
     workflow: Unittests
     token: ${{ secrets.ACCESS_TOKEN }}          
```
And this the Unittests workflow meta data:

```
name: Unittests
on: [workflow_dispatch]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
       ...
```
But when I try and run the first workflow I'll get the following output:
```
Run benc-uk/workflow-dispatch@v1
  with:
    workflow: Unittests
    token: ***
Error: Unable to find workflow 'Unittests' in example/repo 😥
```
Does anyone know a solution for this problem?

**Comment by JayyTurakhia** [comment] 2021-05-13 20:57
Can you please confirm if the workflow file containing Unittests is on master/main/default branch of the repo.
Refer - [https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run](url)

**Comment by ipeshev** [comment] 2022-01-04 08:12
Same here , occurred after failed runs in PR branch, but the workflow is in tact in default branch.

**Comment by perezzini** [comment] 2022-05-23 15:21
Hi! Same problem, here.

**Comment by asafwat** [comment] 2022-08-16 09:09
i had the same issue, after checking this comment 

https://github.com/benc-uk/workflow-dispatch/issues/1#issuecomment-657763660

it turn out that for some reason the workflow name started with a small letter when i queried github api, although the name started with a capital letter in my workflow file, so i deleted the workflow from master and add it back again and this time i got the correct name from github api and the invoke action worked.

worth to check, it could be the case.

**Comment by santunioni** [comment] 2022-10-19 16:42
Using the filename is a more stable solution. Can you change in your side?
Example:
```yaml
 - name: Invoke unit test workflow
   uses: benc-uk/workflow-dispatch@v1
   with:
     workflow: unittests.yaml
     token: ${{ secrets.ACCESS_TOKEN }}     
```

**Comment by benc-uk** [comment] 2022-10-28 16:46
Closing, as v1.2 onwards you can use the filename to trigger workflows

**Closed by benc-uk** 2022-10-28 16:46 UTC

**Comment by yolu-kxs** [comment] 2022-12-17 00:43
@benc-uk it doesn't work in v1.2.1

**Comment by benc-uk** [comment] 2022-12-17 08:36
> @benc-uk it doesn't work in v1.2.1

1.2.1 has been superceded by the latest release 1.2.2

**Comment by bjoernw** [comment] 2023-03-22 19:58
This is still a sporadic issue on 1.2.2

**Comment by benc-uk** [comment] 2023-03-25 09:43
If it's sporadic, then the issue is probably the GitHub API
That's not something I can control!

**Comment by andreagalle** [comment] 2024-04-04 01:22
Could it be an issue if my workflow filename ends with `.yml` rather than `.yaml` ?
